[package]
name = "eyetrackvr-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-literal = "0.4.1"
tokio = { version = "1.35.1", features = ["full"] }
tokio-serial = "5.4.4"
