[package]
name = "eyetrackvr-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-broadcast = "0.7.0"
chrono = "0.4.33"
clap = { version = "4.5.4", features = ["derive"] }
const_format = "0.2.34"
env_logger = "0.11.1"
futures = "0.3.30"
hex-literal = "0.4.1"
hyper = { version = "=0.14.28", features = ["client", "server", "http1", "stream", "tcp"] }
image = "0.24.8"
imgui = { version = "0.11.0", optional = true }
imgui-wgpu = { version = "0.24.0", optional = true }
imgui-winit-support = { version = "0.11.0", optional = true }
mime = "0.3.17"
multipart-stream = "0.1.2"
ndarray = "0.16.1"
nokhwa = { version = "0.10.7", default-features = false, features = ["input-native"]}
one-euro-rs = { git = "https://github.com/pembem22/one-euro-rs.git", branch = "develop" }
ort = { version = "=2.0.0-rc.9", optional = true }
pollster = "0.3.0"
rosc = "0.10.1"
serde_json = "1.0.116"
tokio = { version = "1.35.1", features = ["full"] }
tokio-serial = "5.4.4"
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.10", features = ["codec"] }
wgpu = { version = "0.17.2", optional = true }
winit = { version = "0.27.5", optional = true }

[features]
default = ["inference", "gui"]
inference = ["dep:ort"]
gui = ["dep:imgui", "dep:imgui-wgpu", "dep:imgui-winit-support", "dep:wgpu", "dep:winit"]
