[package]
name = "eyetrackvr-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.33"
env_logger = "0.11.1"
hex-literal = "0.4.1"
hyper = { version = "=0.14.28", features = ["client", "http1", "stream", "tcp"] }
image = "0.24.8"
imgui = "0.11.0"
imgui-wgpu = "0.24.0"
imgui-winit-support = "0.11.0"
mime = "0.3.17"
multipart-stream = "0.1.2"
one-euro-rs = "0.2.0"
onnxruntime = "0.0.14"
pollster = "0.3.0"
rosc = "0.10.1"
tokio = { version = "1.35.1", features = ["full"] }
tokio-serial = "5.4.4"
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.10", features = ["codec"] }
wgpu = "0.17.2"
winit = "0.27.5"
